### PR TITLE
Accept BaseAccount as generic in `ISmartAccountProvider`

### PR DESCRIPTION
**Pull request by ManaOmlabs**

### CODE REVIEW

**Comment by ManaOmlabs** [comment]
@moldy530 as per the request :)

**Comment by moldy530** [comment]
I'm only seeing the changes to the exports here, but not the interface change 🤔

**Comment by moldy530** [comment]
but the fix looks good to me

**Review by moldy530 — APPROVED** [review]

**Comment by ManaOmlabs** [comment]
Yeah realized i actually don't need it. Please do merge and release.

**Comment by moldy530** [comment]
just deployed these changes

**Pull request merged**
