### PR TITLE
feat: update eth_getUserOperationByHash response for pending status

### PR DESCRIPTION
**Pull request by avasisht23**
# Pull Request Checklist

- [x] Did you add new tests and confirm existing tests pass? (`yarn test`)
- [x] Did you update relevant docs? (docs are found in the `site` folder, and guidelines for updating/adding docs can be found in the [contribution guide](https://github.com/alchemyplatform/aa-sdk/blob/main/CONTRIBUTING.md))
- [x] Do your commits follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard?
- [x] Does your PR title also follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard?
- [x] If you have a breaking change, is it [correctly reflected in your commit message](https://www.conventionalcommits.org/en/v1.0.0/#examples)? (e.g. `feat!: breaking change`)
- [x] Did you run lint (`yarn lint:check`) and fix any issues? (`yarn lint:write`)
- [x] Did you follow the [contribution guidelines](https://github.com/alchemyplatform/aa-sdk/blob/main/CONTRIBUTING.md)?

---

## PR-Codex overview
This PR focuses on updating the `UserOperationReceipt` interface in the `types.ts` file. 

### Detailed summary
- Updated `blockNumber` property to accept `null` if the user operation is pending.
- Updated `blockHash` property to accept `null` if the user operation is pending.
- Updated `transactionHash` property to accept `null` if the user operation is pending.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by avasisht23** [comment]
Per: https://github.com/eth-infinitism/account-abstraction/pull/382/files

**Review by moldy530 — APPROVED** [review]

**Comment by denniswon** [comment]
should we update the doc for `eth_getUserOperationByHash` as well?

**Comment by avasisht23** [comment]
> should we update the doc for `eth_getUserOperationByHash` as well?
@denniswon there's no doc that goes to this level of granularity on the type (see the method [doc](https://accountkit.alchemy.com/packages/aa-core/provider/getUserOperationByHash.html#promise-useroperationresponse-null)).

Ava/Sahil are working getting types in and I'll let them know accordingly.

**Comment by denniswon** [comment]
is this pr good to merge ? @avasisht23 @moldy530

**Comment by avasisht23** [comment]
unsure if this is necessary anymore, closing

**Pull request closed without merging**
