### PR TITLE
feat: add fordefi signer to aa-signers

### PR DESCRIPTION
**Pull request by gilmeir-arnac**
# Pull Request Checklist

- [x] Did you add new tests and confirm existing tests pass? (`yarn test`)
- [x] Did you update relevant docs? (docs are found in the `site` folder, and guidelines for updating/adding docs can be found in the [contribution guide](https://github.com/alchemyplatform/aa-sdk/blob/main/CONTRIBUTING.md))
- [x] Do your commits follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard?
- [x] Does your PR title also follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard?
- [x] If you have a breaking change, is it [correctly reflected in your commit message](https://www.conventionalcommits.org/en/v1.0.0/#examples)? (e.g. `feat!: breaking change`)
- [x] Did you run lint (`yarn lint:check`) and fix any issues? (`yarn lint:write`)
- [x] Did you follow the [contribution guidelines](https://github.com/alchemyplatform/aa-sdk/blob/main/CONTRIBUTING.md)?

---

## PR-Codex overview
The focus of this PR is to introduce the Fordefi signer, including authentication, message signing, and typed data signing capabilities.

### Detailed summary
- Added `FordefiSigner` and related types
- Integrated `FordefiWeb3Provider` in the site snippet
- Updated configuration and navigation for Fordefi in the Vitepress site
- Added documentation for `getAddress`, `getAuthDetails`, `signMessage`, and `signTypedData` methods in Fordefi signer

> The following files were skipped due to too many changes: `site/packages/aa-signers/fordefi/signTypedData.md`, `site/packages/aa-signers/fordefi/constructor.md`, `packages/signers/src/fordefi/signer.ts`, `site/packages/aa-signers/fordefi/introduction.md`, `site/smart-accounts/signers/fordefi.md`, `packages/signers/src/fordefi/__tests__/signer.test.ts`, `yarn.lock`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by gilmeir-arnac** [comment]
There are major diffs between `development` and `main`, seems like the reason checks fail are the significant difference.
Please guide me if I am missing anything.

For example the node version on `development` is older than in `main`.
* main: [`>=16`](https://github.com/alchemyplatform/aa-sdk/blob/main/package.json#L6)
* development: [`>=18.16`](https://github.com/alchemyplatform/aa-sdk/blob/development/package.json#L6)

Since our dependency supports `>=18` and this will eventually arrive to `main` I have edited `package.json` to reflect the same engine on `main` to avoid unnecessary adjustments just for the temporary `development` branch. 

Another error I encountered which seems unrelated:
```bash
➜  alchemy-aa-sdk git:(gil/fordefi-signer-to-development) ✗ yarn build
yarn run v1.22.22
$ lerna run build --ignore=alchemy-daapp --ignore=aa-simple-dapp
lerna notice cli v6.6.2
lerna notice filter excluding ["alchemy-daapp","aa-simple-dapp"]
lerna info filter [ '!alchemy-daapp', '!aa-simple-dapp' ]
lerna info run Using the "ignore" option when Nx targets are configured will exclude only tasks that are not determined to be required by Nx. See https://lerna.js.org/docs/lerna6-obsolete-options#--ignore for details.

    ✔  docs:build  [existing outputs match the cache, left as is]

    ✖  @alchemy/aa-core:build
$ ts-node-esm ./inject-version.ts
       TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/gilmeir/projects/alchemy-aa-sdk/packages/core/inject-version.ts

**Comment by gilmeir-arnac** [comment]
Hi Team @moldy530 @rthomare @dancoombs @mokok123 
Could you kindly approve gh actions run and review the PR please?

I initially branched out of `main` to gain certainty the feature would work once merged to `main`.
When I applied the changes to the `development`  branch (per the contribution guide) I noticed it is 4 months behind `main` and required backporting the changes. Let me know if I could target `main` directly instead and save the extra hop.

**Comment by moldy530** [comment]
Hey @gilmeir-arnac, I need to update the contribution guide since it's out of date. Using `main` as your base branch is the correct approach, sorry for the confusion

**Comment by gilmeir-arnac** [comment]
Created #665 that targets `main` instead.

**Pull request closed without merging**
