### PR TITLE
chore: migrate to turbo repo to avoid nx issues

### PR DESCRIPTION
**Pull request by moldy530**
# Pull Request Checklist

- [ ] Did you add new tests and confirm existing tests pass? (`yarn test`)
- [ ] Did you update relevant docs? (docs are found in the `site` folder, and guidelines for updating/adding docs can be found in the [contribution guide](https://github.com/alchemyplatform/aa-sdk/blob/main/CONTRIBUTING.md))
- [ ] Do your commits follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard?
- [ ] Does your PR title also follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard?
- [ ] If you have a breaking change, is it [correctly reflected in your commit message](https://www.conventionalcommits.org/en/v1.0.0/#examples)? (e.g. `feat!: breaking change`)
- [ ] Did you run lint (`yarn lint:check`) and fix any issues? (`yarn lint:write`)
- [ ] Did you follow the [contribution guidelines](https://github.com/alchemyplatform/aa-sdk/blob/main/CONTRIBUTING.md)?

---

## PR-Codex overview
This PR primarily updates the project by introducing Turborepo for task management, updating dependencies, and enhancing configuration files. It also modifies several components and scripts to improve build processes and project structure.

### Detailed summary
- Added `turborepo` configuration in `turbo.json`.
- Updated `vocs` dependency version to `^1.0.0-alpha.62`.
- Modified build scripts in `package.json` to use `turbo`.
- Adjusted ESLint configurations and ignored files in `.eslintignore`.
- Enhanced `tailwind.config.cjs` for content paths.
- Updated `README.md` with team-specific instructions.
- Changed `Sidebar.js` logic for active child items.
- Refactored API key handling in smart contract files.
- Updated GitHub workflows to include `TURBO_TOKEN` and `TURBO_TEAM` environment variables.
- Removed obsolete patch file and updated `.gitignore`.

> The following files were skipped due to too many changes: `yarn.lock`, `node_modules/vocs/_lib/vite/.vocs/cache/twoslash.json`, `node_modules/vocs/_lib/vite/.vocs/cache/search.json`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by moldy530** [comment]
* **#1141** <a href="https://app.graphite.dev/github/pr/alchemyplatform/aa-sdk/1141?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @moldy530 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by moldy530** [comment]
False positive on aa-sdk-site deploy. caching seems to break deployments... will dig in

**Comment by moldy530** [comment]
We will continue to use `lerna` to publish packages for now. I looked at using `auto` from intuit, but that library has an issue in repos that have a huge amount of commits at the moment, so will revisit that later.

**Comment by moldy530** [comment]
looking at the logs for this branch, caching reduced build times for the vercel projects by an order of magnitude

**Review by dphilipson — APPROVED** [review]

**Pull request merged**
