### PR TITLE
docs: ran a spellcheck

### PR DESCRIPTION
**Pull request by Dan-Nolan**
# Pull Request Checklist

- [x] Did you add new tests and confirm existing tests pass? (`yarn test`)
- [x] Did you update relevant docs? (docs are found in the `site` folder, and guidelines for updating/adding docs can be found in the [contribution guide](https://github.com/alchemyplatform/aa-sdk/blob/main/CONTRIBUTING.md))
- [x] Do your commits follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard?
- [x] Does your PR title also follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard?
- [x] If you have a breaking change, is it [correctly reflected in your commit message](https://www.conventionalcommits.org/en/v1.0.0/#examples)? (e.g. `feat!: breaking change`)
- [x] Did you run lint (`yarn lint:check`) and fix any issues? (`yarn lint:write`)
- [x] Did you follow the [contribution guidelines](https://github.com/alchemyplatform/aa-sdk/blob/main/CONTRIBUTING.md)?

saw a few typos while reading the docs, ran a spellcheck over it

---

## PR-Codex overview
This PR focuses on fixing typos and inconsistencies in various files. 

### Detailed summary
- Renamed headings and file names to use consistent capitalization.
- Fixed spelling errors in function and parameter names.
- Corrected spelling and formatting in code comments.
- Updated links to match renamed files and headings.

> The following files were skipped due to too many changes: `site/packages/aa-signers/magic/introduction.md`, `site/packages/aa-signers/lit-protocol/authenticate.md`, `site/packages/aa-signers/turnkey/introduction.md`, `site/packages/aa-core/smart-account-client/actions/checkGasSponsorshipEligibility.md`, `site/packages/aa-ethers/account-signer/introduction.md`, `site/signers/guides/custom-signer.md`, `site/packages/aa-ethers/provider-adapter/introduction.md`, `site/packages/aa-core/smart-account-client/index.md`, `site/smart-accounts/custom/contributing.md`, `site/using-smart-accounts/send-user-operations.md`, `site/using-smart-accounts/sponsoring-gas/checking-eligibility.md`, `site/packages/aa-core/smart-account-client/types/userOperationOverrides.md`, `site/getting-started/setup.md`, `site/.vitepress/sidebar/index.ts`, `site/signers/contributing.md`, `site/smart-accounts/modular-account/index.md`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by denniswon — APPROVED** [review]
thank you!

**Comment by denniswon** [comment]
@Dan-Nolan can you run yarn build on your repo so that lint is applied?

**Comment by Dan-Nolan** [comment]
ran yarn lint:check and yarn lint:write but yarn build is giving me a config issue `Error: Could not find any runner configurations in nx.json`

I'll have to brush up on my lerna

**Comment by moldy530** [comment]
Ah the build here is failing because it looks like on forks the API key we use to generate plugins isn't passed through. Everything looks fine otherwise

**Review by moldy530 — DISMISSED** [review]

**Review by moldy530 — APPROVED** [review]

**Comment by denniswon** [comment]
@Dan-Nolan can you please rebase to origin main so that we can merge this pr? thanks!

**Pull request closed without merging**
